// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1
{
    using Models;

    /// <summary>
    /// Employer operations.
    /// </summary>
    public partial interface IEmployer
    {
        /// <summary>
        /// Endpoint for linking an employer to a provider site.
        /// </summary>
        /// <param name='employerProviderSiteLinkRequest'>
        /// Defines the provider site to link to as well as additional
        /// employer information. Note that you can specify the employer
        /// identifier in either the URL or the POST body
        /// </param>
        /// <param name='edsUrn'>
        /// The employer's secondary identifier.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<EmployerProviderSiteLink>> LinkEmployerByEdsUrnWithHttpMessagesAsync(EmployerProviderSiteLinkRequest employerProviderSiteLinkRequest, int edsUrn, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
