#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Vacancy
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Raa.Vacancies;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    
    #line 4 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Common.Constants.ViewModels;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Common.Extensions;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    
    #line 6 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Common.Validators.Extensions;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Common.ViewModels;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Raa.Common;
    
    #line 8 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.Constants.ViewModels;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Vacancy/FurtherVacancyDetails.cshtml")]
    public partial class FurtherVacancyDetails : System.Web.Mvc.WebViewPage<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Vacancy.FurtherVacancyDetailsViewModel>
    {
        public FurtherVacancyDetails()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
  
    var heading = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? "Enter opportunity details" : "Enter further details";
    ViewBag.Title = "Recruit an Apprentice - " + heading;

    var disabledTag = Model.Status.CanManageVacancyDates() ? "disabled=disabled" : "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 19 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 20 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.Partial("ValidationSummary", ViewData.ModelState));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 22 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.VacancyReferenceNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 23 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.Status));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.VacancyType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.WarningsHash));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.ComeFromPreview));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 27 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
Write(Html.HiddenFor(m => m.VacancySource));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" id=\"heading\"");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                           Write(heading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n");

            
            #line 38 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
          
            var workingWeeklabelText = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.WorkingWeek.TraineeshipLabelText : null;
            var workingWeekDataValLength = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.WorkingWeek.TraineeshipTooLongErrorText : VacancyViewModelMessages.WorkingWeek.TooLongErrorText;
            var workingWeekDataValRegex = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.WorkingWeek.TraineeshipWhiteListErrorText : VacancyViewModelMessages.WorkingWeek.WhiteListErrorText;
        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.FormTextAreaFor(m => m.WorkingWeek, workingWeeklabelText, containerHtmlAttributes: new { @baseClassName = "working-week form-group" }, controlHtmlAttributes: new { @class = "form-control-4-4", type = "text", size = 12, data_val_length = workingWeekDataValLength, data_val_regex = workingWeekDataValRegex }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

            
            #line 45 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
         if (Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship)
        {
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.HoursPerWeek));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                     
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                            
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.FormTextFor(m => m.Wage.HoursPerWeek, controlHtmlAttributes: new { @class = "form-control form-control-1-8", type = "tel", size = 12 }));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                                                                                                                         
            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.EditorFor(m => m.WorkingWeekComment, "Comment", Html.GetLabelFor(m => m.WorkingWeekComment, Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.WorkingWeekComment.TraineeshipLabelText : null)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 58 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
         if (Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship)
        {
            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.Type));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                             
            
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.Classification));

            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                       
            
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.CustomType));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                   
            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.PresetText));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                   
            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.Amount));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                               
            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.AmountLowerBound));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.AmountUpperBound));

            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.Unit));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                             
            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.RangeUnit));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                  
            
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.WageTypeReason));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                       
            
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.Wage.HoursPerWeek));

            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                     
            
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.HiddenFor(m => m.WageComment));

            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                               
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <fieldset>\r\n                    <a");

WriteAttribute("name", Tuple.Create(" name=\"", 4199), Tuple.Create("\"", 4268)
            
            #line 77 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 4206), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.Wage.Classification).ToString().ToLower()
            
            #line default
            #line hidden
, 4206), false)
);

WriteLiteral("></a>\r\n                    <h3");

WriteLiteral(" class=\"heading-small sfa-no-top-margin\"");

WriteLiteral(">Wage</h3>\r\n                    <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Wage</legend>\r\n\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4444), Tuple.Create("\"", 4574)
            
            #line 81 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 4452), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.Wage.Type))
            
            #line default
            #line hidden
, 4452), false)
);

WriteLiteral(" data-editable-x=\"\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"national-minimum-wage\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 84 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.Wage.Classification, WageClassification.NationalMinimum, new { id = "national-minimum-wage", aria_controls = "wage-type-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            National Minimum Wage\r\n                        </la" +
"bel>\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-minimum-wage\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.Wage.Classification, WageClassification.ApprenticeshipMinimum, new { id = "apprenticeship-minimum-wage", aria_controls = "wage-type-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            National Minimum Wage for apprentices\r\n            " +
"            </label>\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"custom-wage\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" data-target=\"custom-wage-panel\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 94 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.Wage.Classification, WageClassification.Custom, new { id = "custom-wage", aria_controls = "wage-type-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            Custom wage\r\n                        </label>\r\n\r\n  " +
"                      <div");

WriteLiteral(" id=\"custom-wage-panel\"");

WriteLiteral(" class=\"toggle-content panel panel-border-narrow\"");

WriteLiteral(">\r\n                            <fieldset");

WriteLiteral(" class=\"inline\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Select type</h3>\r\n                                <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Select type</legend>\r\n");

WriteLiteral("                                ");

            
            #line 103 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Wage.CustomType));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                <label");

WriteLiteral(" for=\"custom-wage-fixed\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" data-target=\"custom-wage-fixed-panel\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 106 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.Wage.CustomType, CustomWageType.Fixed, new { id = "custom-wage-fixed", aria_controls = "custom-wage-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    Fixed wage\r\n                               " +
" </label>\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" for=\"custom-wage-range\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" data-target=\"custom-wage-range-panel\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 111 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.Wage.CustomType, CustomWageType.Ranged, new { id = "custom-wage-range", aria_controls = "custom-wage-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    Wage range\r\n                               " +
" </label>\r\n                            </fieldset>\r\n\r\n                          " +
"  <div");

WriteLiteral(" id=\"custom-wage-fixed-panel\"");

WriteLiteral(" class=\"toggle-content panel panel-border-narrow sfa-medium-top-margin form-group" +
"\"");

WriteLiteral(">\r\n                                <fieldset>\r\n                                  " +
"  <p");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">");

            
            #line 118 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                    Write(Html.Label(WageViewModelMessages.AmountMessages.HelpText));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("                                        ");

            
            #line 119 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.ValidationMessageWithSeverityFor(m => m.Wage.Amount, Html.GetValidationType(m => m.Wage.Amount)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <p");

WriteLiteral(" class=\"sfa-display-inline\"");

WriteLiteral(">£</p>\r\n                                        <a");

WriteAttribute("name", Tuple.Create(" name=\"", 8023), Tuple.Create("\"", 8084)
            
            #line 122 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8030), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.Wage.Amount).ToString().ToLower()
            
            #line default
            #line hidden
, 8030), false)
);

WriteLiteral("></a>\r\n");

WriteLiteral("                                        ");

            
            #line 123 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.LabelFor(m => m.Wage.Amount, new { @class = "sfa-hide" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 124 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.TextBoxFor(m => m.Wage.Amount, new { @class="form-control form-control-1-4 sfa-form-control-1-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                                        ");

            
            #line 126 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.DropDownListFor(m => m.Wage.Unit, Model.WageUnits, new { @class = "form-control sfa-form-control-auto" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                 </fieldset>\r\n                            </div" +
">\r\n\r\n                            <div");

WriteLiteral(" id=\"custom-wage-range-panel\"");

WriteLiteral(" class=\"toggle-content panel panel-border-narrow sfa-medium-top-margin form-group" +
"\"");

WriteLiteral(" >\r\n                                <fieldset>\r\n                                 " +
"   <p");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                    Write(Html.Label(WageViewModelMessages.AmountRangeMessages.HelpText, new { @class = "form-hint" }));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("                                        ");

            
            #line 133 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.Wage.AmountLowerBound)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 134 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.Wage.AmountUpperBound)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 135 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.ValidationMessageWithSeverityFor(m => m.Wage.AmountLowerBound, Html.GetValidationType(m => m.Wage.AmountLowerBound)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 136 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.ValidationMessageWithSeverityFor(m => m.Wage.AmountUpperBound, Html.GetValidationType(m => m.Wage.AmountUpperBound)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <p");

WriteLiteral(" class=\"sfa-display-inline\"");

WriteLiteral(">£</p>\r\n\r\n                                        <a");

WriteAttribute("name", Tuple.Create(" name=\"", 9729), Tuple.Create("\"", 9800)
            
            #line 140 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 9736), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.Wage.AmountLowerBound).ToString().ToLower()
            
            #line default
            #line hidden
, 9736), false)
);

WriteLiteral("></a>\r\n");

WriteLiteral("                                        ");

            
            #line 141 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.LabelFor(m => m.Wage.AmountLowerBound, new { @class = "sfa-hide" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 142 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.TextBoxFor(m => m.Wage.AmountLowerBound, new { @class = "form-control form-control-1-4 sfa-form-control-1-4", type = "number", size = 12, placeholder = "min" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <p");

WriteLiteral(" class=\"sfa-display-inline\"");

WriteLiteral("><span");

WriteLiteral(" class=\"secondary-text\"");

WriteLiteral(" style=\"padding:0 0.5em;\"");

WriteLiteral(">to</span> £</p>\r\n\r\n                                        <a");

WriteAttribute("name", Tuple.Create(" name=\"", 10318), Tuple.Create("\"", 10389)
            
            #line 146 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 10325), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.Wage.AmountUpperBound).ToString().ToLower()
            
            #line default
            #line hidden
, 10325), false)
);

WriteLiteral("></a>\r\n");

WriteLiteral("                                        ");

            
            #line 147 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.LabelFor(m => m.Wage.AmountUpperBound, new { @class = "sfa-hide" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 148 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.TextBoxFor(m => m.Wage.AmountUpperBound, new { @class = "form-control form-control-1-4 sfa-form-control-1-4", type = "number", size = 12, placeholder = "max" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                                        ");

            
            #line 150 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                   Write(Html.DropDownListFor(m => m.Wage.RangeUnit, Model.WageUnits, new { @class = "form-control sfa-form-control-auto" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </fieldset>\r\n                            </div>" +
"\r\n                        </div>\r\n                        <p");

WriteLiteral(" class=\"form-block\"");

WriteLiteral(">or</p>\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"preset-text\"");

WriteLiteral(" class=\"block-label selection-button-radio \"");

WriteLiteral(" data-target=\"preset-text-panel\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 157 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.Wage.Classification, WageClassification.PresetText, new { id = "preset-text", aria_controls = "wage-type-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            Choose a text description of the wage\r\n            " +
"            </label>\r\n");

WriteLiteral("                        ");

            
            #line 160 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Wage.Classification));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" id=\"preset-text-panel\"");

WriteLiteral(" class=\"toggle-content blocklabel-content panel panel-border-narrow clearfix\"");

WriteLiteral(">\r\n                            <fieldset");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 163 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           Write(Html.DropDownListFor(m => m.Wage.PresetText, Model.WageTextPresets, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </fieldset>\r\n                            <fieldset");

WriteAttribute("class", Tuple.Create(" class=\"", 12011), Tuple.Create("\"", 12160)
, Tuple.Create(Tuple.Create("", 12019), Tuple.Create("form-group", 12019), true)
            
            #line 165 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 12029), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.Wage.WageTypeReason))
            
            #line default
            #line hidden
, 12030), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 166 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           Write(Html.Label(WageViewModelMessages.WageTypeReason.LabelText, new { @class = "form-label-bold" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 167 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           Write(Html.Label(WageViewModelMessages.WageTypeReason.HelpText, new { @class = "form-hint" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 168 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                           Write(Html.FormTextAreaFor(m => m.Wage.WageTypeReason,
                                    string.Empty,
                                    controlHtmlAttributes: new
                                    {
                                        @class = "form-control-3-4",
                                        type = "text",
                                        size = 12,
                                        data_val_length = WageViewModelMessages.WageTypeReason.TooLongErrorText,
                                        data_val_length_max = 240,
                                        data_val_regex = Whitelists.FreetextWhitelist.RegularExpression
                                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </fieldset>\r\n                        </div>\r\n      " +
"              </div>\r\n                </fieldset>\r\n            </div>\r\n");

            
            #line 184 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 184 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.EditorFor(m => m.WageComment, "Comment", Html.GetLabelFor(m => m.WageComment)));

            
            #line default
            #line hidden
            
            #line 184 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                                                                
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <fieldset ");

            
            #line 187 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
             Write(disabledTag);

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Expected duration</legend>\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 13539), Tuple.Create("\"", 13679)
, Tuple.Create(Tuple.Create("", 13547), Tuple.Create("form-group", 13547), true)
            
            #line 189 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 13557), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.Duration))
            
            #line default
            #line hidden
, 13558), false)
);

WriteLiteral(">\r\n                \r\n                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 13719), Tuple.Create("\"", 13777)
            
            #line 191 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
, Tuple.Create(Tuple.Create("", 13726), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.Duration).ToString().ToLower()
            
            #line default
            #line hidden
, 13726), false)
);

WriteLiteral("></a>\r\n");

WriteLiteral("                ");

            
            #line 192 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
           Write(Html.LabelFor(m => m.Duration, new { @class = "form-label-bold" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 193 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
           Write(Html.ValidationMessageWithSeverityFor(m => m.Duration, Html.GetValidationType(m => m.Duration)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 194 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
           Write(Html.TextBoxFor(m => m.Duration, new { @class = "form-control-1-8 form-control", type = "tel", size = 12 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 195 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
           Write(Html.DropDownListFor(m => m.DurationType, Model.DurationTypes, new { @class = "form-control sfa-form-control-auto" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n");

            
            #line 198 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 198 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
             if (Model.VacancySource != VacancySource.Raa)
            {
                
            
            #line default
            #line hidden
            
            #line 200 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
           Write(Html.FormTextAreaFor(model => model.ExpectedDuration, controlHtmlAttributes: new { type = "text", rows="1", @class = "form-control-1-2" }));

            
            #line default
            #line hidden
            
            #line 200 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
                                                                                                                                                           
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 202 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.EditorFor(m => m.DurationComment, "Comment", Html.GetLabelFor(m => m.DurationComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </fieldset>\r\n\r\n");

WriteLiteral("        ");

            
            #line 205 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.EditorFor(m => m.VacancyDatesViewModel.ClosingDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 206 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.EditorFor(m => m.VacancyDatesViewModel.ClosingDateComment, "Comment", Html.GetLabelFor(m => m.VacancyDatesViewModel.ClosingDateComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 208 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.EditorFor(m => m.VacancyDatesViewModel.PossibleStartDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 209 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
   Write(Html.EditorFor(m => m.VacancyDatesViewModel.PossibleStartDateComment, "Comment", Html.GetLabelFor(m => m.VacancyDatesViewModel.PossibleStartDateComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div ");

            
            #line 211 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
        Write(disabledTag);

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 212 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 212 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
              
                var longDescriptionlabelText = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.LongDescription.TraineeshipLabelText : null;
                var longDescriptionDataValLength = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.LongDescription.TraineeshipTooLongErrorText : VacancyViewModelMessages.LongDescription.TooLongErrorText;
                var longDescriptionDataValRegex = Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.LongDescription.TraineeshipWhiteListInvalidCharacterErrorText : VacancyViewModelMessages.LongDescription.WhiteListInvalidCharacterErrorText;
            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 217 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.FormTextAreaFor(m => m.LongDescription, longDescriptionlabelText, controlHtmlAttributes: new { id = "LongDescription", @class = "ckeditor", type = "text", size = 12, rows = 7, data_val_length = longDescriptionDataValLength, data_val_regex = longDescriptionDataValRegex }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 218 "..\..\Views\Shared\DisplayTemplates\Vacancy\FurtherVacancyDetails.cshtml"
       Write(Html.EditorFor(m => m.LongDescriptionComment, "Comment", Html.GetLabelFor(m => m.LongDescriptionComment, Model.VacancyType == SFA.Apprenticeships.Domain.Entities.Raa.Vacancies.VacancyType.Traineeship ? VacancyViewModelMessages.LongDescriptionComment.TraineeshipLabelText : null)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
