#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Vacancy
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Raa.Vacancies;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.Extensions;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.ViewModels.Vacancy;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Vacancy/TrainingDetails.cshtml")]
    public partial class TrainingDetails : System.Web.Mvc.WebViewPage<TrainingDetailsViewModel>
    {
        public TrainingDetails()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
  
    ViewBag.Title = "Recruit an Apprentice - Apprenticeship training";

    const string selected = "selected";

    var frameworksSelected = Model.TrainingType == TrainingType.Frameworks ? selected : null;
    var standardsSelected = Model.TrainingType == TrainingType.Standards ? selected : null;


    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
Write(Html.Partial("ValidationSummary", ViewData.ModelState));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                           


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\r\n                Enter training details\r\n            </h1>\r\n        </div>\r\n   " +
" </div>\r\n");

            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.HiddenFor(m => m.VacancyReferenceNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.HiddenFor(m => m.Status));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.HiddenFor(m => m.VacancyType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.HiddenFor(m => m.ComeFromPreview));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.HiddenFor(m => m.VacancySource));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
              
                var isAnyTrainingTypeSelected = Model.TrainingType != TrainingType.Unknown;
                var isFramework = isAnyTrainingTypeSelected && Model.TrainingType == TrainingType.Frameworks;
                var isStandard = isAnyTrainingTypeSelected && Model.TrainingType == TrainingType.Standards;
                var frameworkClass = isFramework ? "" : "hide-nojs";
                var standardClass = isStandard ? "" : "hide-nojs";
            
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 42 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                     if (Model.VacancyType == VacancyType.Traineeship)
            {
                        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.TrainingType));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                            
                        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.FrameworkCodeName));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                 
                        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.FrameworkCodeNameComment));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                        
                        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.StandardId));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                          
                        
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.StandardIdComment));

            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                 
                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.ApprenticeshipLevel));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                   
                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.HiddenFor(m => m.ApprenticeshipLevelComment));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                          


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2218), Tuple.Create("\"", 2364)
, Tuple.Create(Tuple.Create("", 2226), Tuple.Create("form-group", 2226), true)
            
            #line 52 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 2236), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.SectorCodeName))
            
            #line default
            #line hidden
, 2237), false)
);

WriteLiteral(">\r\n                            <a");

WriteAttribute("name", Tuple.Create(" name=\"", 2398), Tuple.Create("\"", 2462)
            
            #line 53 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 2405), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.SectorCodeName).ToString().ToLower()
            
            #line default
            #line hidden
, 2405), false)
);

WriteLiteral("></a>\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 2504), Tuple.Create("\"", 2546)
            
            #line 54 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 2510), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.SectorCodeName)
            
            #line default
            #line hidden
, 2510), false)
);

WriteLiteral(" class=\"form-label-bold\"");

WriteLiteral(">Traineeship sector</label>\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.SectorCodeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.DropDownListFor(m => m.SectorCodeName, Model.Sectors, new { @class = "form-control form-control-2-3 chosen-select" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 57 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.SectorCodeNameComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 59 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                   Write(Html.EditorFor(m => m.SectorCodeNameComment, "Comment", Html.GetLabelFor(m => m.SectorCodeNameComment)));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                                                                                
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3180), Tuple.Create("\"", 3368)
, Tuple.Create(Tuple.Create("", 3188), Tuple.Create("form-group", 3188), true)
            
            #line 63 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 3198), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.TrainingType))
            
            #line default
            #line hidden
, 3199), false)
, Tuple.Create(Tuple.Create(" ", 3324), Tuple.Create("inline", 3325), true)
, Tuple.Create(Tuple.Create(" ", 3331), Tuple.Create("clearfix", 3332), true)
, Tuple.Create(Tuple.Create(" ", 3340), Tuple.Create("blocklabel-single", 3341), true)
, Tuple.Create(Tuple.Create(" ", 3358), Tuple.Create("hide-nojs", 3359), true)
);

WriteLiteral(">\r\n                            <fieldset");

WriteLiteral(" class=\"inline\"");

WriteLiteral(">\r\n                                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 3461), Tuple.Create("\"", 3523)
            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 3468), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.TrainingType).ToString().ToLower()
            
            #line default
            #line hidden
, 3468), false)
);

WriteLiteral("></a>\r\n                                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Apprenticeship type</h3>\r\n                                <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Apprenticeship type</legend>\r\n\r\n                                <p");

WriteLiteral(" id=\"frameworks-standards-explained\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">Select a framework if you only offer this type of apprenticeship training.</span" +
">\r\n                                </p>\r\n                                <p>\r\n  " +
"                                  <span");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">Alternatively, if you also deliver the new <a");

WriteLiteral(" href=\"https://www.gov.uk/government/collections/apprenticeship-standards\"");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">apprenticeship standards</a>, you can choose a standard job role instead.</span>" +
"\r\n</p>\r\n\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" data-target=\"training-type-frameworks-panel\"");

WriteLiteral(" for=\"training-type-frameworks\"");

WriteAttribute("class", Tuple.Create(" class=\"", 4498), Tuple.Create("\"", 4560)
, Tuple.Create(Tuple.Create("", 4506), Tuple.Create("block-label", 4506), true)
, Tuple.Create(Tuple.Create(" ", 4517), Tuple.Create("selection-button-radio", 4518), true)
            
            #line 77 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                            , Tuple.Create(Tuple.Create(" ", 4540), Tuple.Create<System.Object, System.Int32>(frameworksSelected
            
            #line default
            #line hidden
, 4541), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.TrainingType, TrainingType.Frameworks, new { id = "training-type-frameworks", aria_controls = "training-type-frameworks-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    Framework\r\n                                " +
"</label>\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" data-target=\"training-type-standards-panel\"");

WriteLiteral(" for=\"training-type-standards\"");

WriteAttribute("class", Tuple.Create(" class=\"", 5049), Tuple.Create("\"", 5110)
, Tuple.Create(Tuple.Create("", 5057), Tuple.Create("block-label", 5057), true)
, Tuple.Create(Tuple.Create(" ", 5068), Tuple.Create("selection-button-radio", 5069), true)
            
            #line 82 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                          , Tuple.Create(Tuple.Create(" ", 5091), Tuple.Create<System.Object, System.Int32>(standardsSelected
            
            #line default
            #line hidden
, 5092), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 83 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.TrainingType, TrainingType.Standards, new { id = "training-type-standards", aria_controls = "training-type-standards-panel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    Standard\r\n                                <" +
"/label>\r\n\r\n                            </fieldset>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.TrainingType));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 91 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                        <noscript>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Apprenticeship type</h3>\r\n\r\n                                <p");

WriteLiteral(" id=\"frameworks-standards-explained\"");

WriteLiteral(">\r\n                                    Select a framework if you only offer this " +
"type of apprenticeship training.<br />\r\n                                    Alte" +
"rnatively, if you also deliver the new <a");

WriteLiteral(" href=\"https://www.gov.uk/government/collections/apprenticeship-standards\"");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">apprenticeship standards</a>, you can choose a standard job role instead.\r\n     " +
"                           </p>\r\n\r\n");

            
            #line 101 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                 if (isFramework)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <label");

WriteLiteral(" class=\"unselected-apprenticeship-type\"");

WriteLiteral(">Framework</label>\r\n");

            
            #line 104 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" id=\"selectFramework\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button sfa-button-secondary\"");

WriteLiteral(" name=\"TrainingDetails\"");

WriteLiteral(" value=\"SelectFramework\"");

WriteLiteral(">Framework</button>\r\n");

            
            #line 108 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 110 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 110 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                 if (isStandard)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <label");

WriteLiteral(" class=\"unselected-apprenticeship-type\"");

WriteLiteral(">Standard</label>\r\n");

            
            #line 113 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" id=\"selectStandard\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button sfa-button-secondary\"");

WriteLiteral(" name=\"TrainingDetails\"");

WriteLiteral(" value=\"SelectStandard\"");

WriteLiteral(">Standard</button>\r\n");

            
            #line 117 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </noscript>\r\n");

            
            #line 120 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"training-type-frameworks-panel\"");

WriteAttribute("class", Tuple.Create(" class=\"", 7384), Tuple.Create("\"", 7422)
, Tuple.Create(Tuple.Create("", 7392), Tuple.Create("toggle-content", 7392), true)
            
            #line 121 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
      , Tuple.Create(Tuple.Create(" ", 7406), Tuple.Create<System.Object, System.Int32>(frameworkClass
            
            #line default
            #line hidden
, 7407), false)
);

WriteLiteral(">\r\n                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7458), Tuple.Create("\"", 7607)
, Tuple.Create(Tuple.Create("", 7466), Tuple.Create("form-group", 7466), true)
            
            #line 122 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 7476), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.FrameworkCodeName))
            
            #line default
            #line hidden
, 7477), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 7645), Tuple.Create("\"", 7712)
            
            #line 123 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 7652), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.FrameworkCodeName).ToString().ToLower()
            
            #line default
            #line hidden
, 7652), false)
);

WriteLiteral("></a>\r\n                                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 7758), Tuple.Create("\"", 7803)
            
            #line 124 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 7764), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.FrameworkCodeName)
            
            #line default
            #line hidden
, 7764), false)
);

WriteLiteral(" class=\"form-label-bold\"");

WriteLiteral(">Apprenticeship framework</label>\r\n");

WriteLiteral("                                ");

            
            #line 125 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                           Write(Html.DropDownListFor(m => m.FrameworkCodeName, Model.SectorsAndFrameworks, new { @class = "form-control chosen-select form-control-2-3" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 126 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                           Write(Html.ValidationMessageFor(m => m.FrameworkCodeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 128 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.FrameworkCodeNameComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 129 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.EditorFor(m => m.FrameworkCodeNameComment, "Comment", Html.GetLabelFor(m => m.FrameworkCodeNameComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8421), Tuple.Create("\"", 8572)
, Tuple.Create(Tuple.Create("", 8429), Tuple.Create("form-group", 8429), true)
            
            #line 131 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 8439), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.ApprenticeshipLevel))
            
            #line default
            #line hidden
, 8440), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 8610), Tuple.Create("\"", 8679)
            
            #line 132 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8617), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.ApprenticeshipLevel).ToString().ToLower()
            
            #line default
            #line hidden
, 8617), false)
);

WriteLiteral("></a>\r\n                                <label");

WriteLiteral(" class=\"form-label-bold sfa-small-bottom-margin\"");

WriteLiteral(">Apprenticeship level</label>\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" for=\"apprenticeship-level-intermediate\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 136 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Intermediate, new { id = "apprenticeship-level-intermediate", aria_labelledby = "apprenticeship-level-label" }));

            
            #line default
            #line hidden
WriteLiteral(" Intermediate\r\n                                </label>\r\n                        " +
"        ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" for=\"apprenticeship-level-advanced\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 140 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Advanced, new { id = "apprenticeship-level-advanced", aria_labelledby = "apprenticeship-level-label" }));

            
            #line default
            #line hidden
WriteLiteral(" Advanced\r\n                                </label>\r\n                            " +
"    ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" for=\"apprenticeship-level-higher\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 144 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Higher, new { id = "apprenticeship-level-higher", aria_labelledby = "apprenticeship-level-label" }));

            
            #line default
            #line hidden
WriteLiteral(" Higher\r\n                                </label>\r\n                              " +
"  ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" for=\"apprenticeship-level-degree\"");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 148 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                               Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Degree, new { id = "apprenticeship-level-degree", aria_labelledby = "apprenticeship-level-label" }));

            
            #line default
            #line hidden
WriteLiteral(" Degree\r\n                                </label>\r\n");

WriteLiteral("                                ");

            
            #line 150 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                           Write(Html.ValidationMessageFor(m => m.ApprenticeshipLevel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 152 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.ApprenticeshipLevelComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 153 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.EditorFor(m => m.ApprenticeshipLevelComment, "Comment", Html.GetLabelFor(m => m.ApprenticeshipLevelComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        </div>\r\n");

            
            #line 156 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"training-type-standards-panel\"");

WriteAttribute("class", Tuple.Create(" class=\"", 11142), Tuple.Create("\"", 11179)
, Tuple.Create(Tuple.Create("", 11150), Tuple.Create("toggle-content", 11150), true)
            
            #line 157 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
    , Tuple.Create(Tuple.Create(" ", 11164), Tuple.Create<System.Object, System.Int32>(standardClass
            
            #line default
            #line hidden
, 11165), false)
);

WriteLiteral(">\r\n                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 11215), Tuple.Create("\"", 11357)
, Tuple.Create(Tuple.Create("", 11223), Tuple.Create("form-group", 11223), true)
            
            #line 158 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 11233), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.StandardId))
            
            #line default
            #line hidden
, 11234), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 11395), Tuple.Create("\"", 11455)
            
            #line 159 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 11402), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId).ToString().ToLower()
            
            #line default
            #line hidden
, 11402), false)
);

WriteLiteral("></a>\r\n                                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 11501), Tuple.Create("\"", 11539)
            
            #line 160 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 11507), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 11507), false)
);

WriteLiteral(" class=\"form-label-bold\"");

WriteLiteral(">Apprenticeship standard</label>\r\n");

WriteLiteral("                                ");

            
            #line 161 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                           Write(Html.ValidationMessageFor(m => m.StandardId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <select");

WriteLiteral(" class=\"form-control form-control-2-3\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11754), Tuple.Create("\"", 11793)
            
            #line 162 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
   , Tuple.Create(Tuple.Create("", 11761), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 11761), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 11794), Tuple.Create("\"", 11831)
            
            #line 162 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                         , Tuple.Create(Tuple.Create("", 11799), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 11799), false)
);

WriteLiteral(" class=\"form-control form-control-2-3 chosen-select\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Choose from the list of standards</option>\r\n");

            
            #line 164 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 164 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                     foreach (var standardGroup in Model.Standards.GroupBy(s => s.Sector))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <optgroup");

WriteAttribute("label", Tuple.Create(" label=\"", 12180), Tuple.Create("\"", 12206)
            
            #line 166 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 12188), Tuple.Create<System.Object, System.Int32>(standardGroup.Key
            
            #line default
            #line hidden
, 12188), false)
);

WriteLiteral(">\r\n");

            
            #line 167 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 167 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                             foreach (var standard in standardGroup)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 12398), Tuple.Create("\"", 12418)
            
            #line 169 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
, Tuple.Create(Tuple.Create("", 12406), Tuple.Create<System.Object, System.Int32>(standard.Id
            
            #line default
            #line hidden
, 12406), false)
);

WriteLiteral(" ");

            
            #line 169 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                         Write(standard.Id == Model.StandardId ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-apprenticeship-level=\"");

            
            #line 169 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                                                                                                        Write(standard.ApprenticeshipLevel);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                                    ");

            
            #line 170 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                               Write(standard.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </option>\r\n");

            
            #line 172 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </optgroup>\r\n");

            
            #line 174 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 177 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.ValidationMessageFor(m => m.StandardIdComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 178 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                       Write(Html.EditorFor(m => m.StandardIdComment, "Comment", Html.GetLabelFor(m => m.StandardIdComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 180 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 180 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                              
                                var style = Model.StandardId.HasValue ? "" : "display: none";
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group hide-nojs\"");

WriteLiteral(" id=\"apprenticeship-level-container\"");

WriteAttribute("style", Tuple.Create(" style=\"", 13345), Tuple.Create("\"", 13359)
            
            #line 184 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                        , Tuple.Create(Tuple.Create("", 13353), Tuple.Create<System.Object, System.Int32>(style
            
            #line default
            #line hidden
, 13353), false)
);

WriteLiteral(">\r\n                                <h3");

WriteLiteral(" class=\"heading-small sfa-no-margins\"");

WriteLiteral(">Apprenticeship level</h3>\r\n                                <p");

WriteLiteral(" id=\"apprenticeship-level-name\"");

WriteLiteral(" class=\"sfa-no-margins\"");

WriteLiteral(">");

            
            #line 186 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                                                                    Write(Html.DisplayFor(m => m.ApprenticeshipLevel));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 189 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 191 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.FormTextAreaFor(m => m.TrainingProvided, controlHtmlAttributes: new { @class = "form-control form-control-3-4 form-textarea-medium ckeditor", type = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 192 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.ValidationMessageFor(m => m.TrainingProvidedComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 193 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
       Write(Html.EditorFor(m => m.TrainingProvidedComment, "Comment", Html.GetLabelFor(m => m.TrainingProvidedComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <fieldset>\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Contact details</h3>\r\n                <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Contact details</legend>\r\n                <p");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">If you would like candidates to be able to contact you about this vacancy, fill " +
"in this section</p>\r\n\r\n");

WriteLiteral("                ");

            
            #line 200 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
           Write(Html.FormTextFor(
            m => m.ContactName,
            controlHtmlAttributes: new { type = "text", spellcheck = "false" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                ");

            
            #line 204 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
           Write(Html.FormTextFor(
            m => m.ContactNumber,
            controlHtmlAttributes: new { @class = "form-label-bold", type = "tel", spellcheck = "false" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                ");

            
            #line 208 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
           Write(Html.FormTextFor(
            m => m.ContactEmail,
            controlHtmlAttributes: new { type = "email", spellcheck = "false" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                ");

            
            #line 212 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
           Write(Html.ValidationMessageFor(m => m.ContactDetailsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 213 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"
           Write(Html.EditorFor(m => m.ContactDetailsComment, "Comment", Html.GetLabelFor(m => m.ContactDetailsComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                \r\n            </fieldset>\r\n        </div>\r\n    </div>\r\n");

            
            #line 218 "..\..\Views\Shared\DisplayTemplates\Vacancy\TrainingDetails.cshtml"

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
