#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.ApprenticeshipApplication
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Applications;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    
    #line 2 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
    using SFA.Apprenticeships.Web.Candidate.Extensions;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Common.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Common.Views.Shared.DisplayTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApprenticeshipApplication/WhatHappensNext.cshtml")]
    public partial class WhatHappensNext : System.Web.Mvc.WebViewPage<SFA.Apprenticeships.Web.Candidate.ViewModels.Applications.WhatHappensNextApprenticeshipViewModel>
    {
        public WhatHappensNext()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
  
    ViewBag.Title = "Apprenticeship application submitted - Find an apprenticeship";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"govuk-box-highlight sfa-govuk-box-highlight\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\"bold-large sfa-large-bottom-margin\"");

WriteLiteral(">Apprenticeship application submitted</h1>\r\n        </div>\r\n\r\n        <p><i");

WriteLiteral(" class=\"fa fa-envelope-o\"");

WriteLiteral("></i>We\'ve sent you an email confirming your <strong");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                         Write(Html.DisplayFor(m => m.VacancyTitle));

            
            #line default
            #line hidden
WriteLiteral("</strong> application</p>\r\n        \r\n        <p> You can also <a");

WriteLiteral(" title=\"Track the progress of your application\"");

WriteAttribute("href", Tuple.Create(" href=\"", 865), Tuple.Create("\"", 921)
            
            #line 18 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
  , Tuple.Create(Tuple.Create("", 872), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.MyApplications)
            
            #line default
            #line hidden
, 872), false)
);

WriteLiteral(">track the progress</a> of your application</p>\r\n        <p>You’ll be contacted i" +
"f you’ve been selected for the next stage of the application process.</p>\r\n     " +
"   <details>\r\n            <summary><span");

WriteLiteral(" class=\"summary\"");

WriteLiteral(">Contact the provider</span></summary>\r\n            <div");

WriteLiteral(" class=\"detail-content\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                   Write(Model.ProviderContactInfo);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </details>\r\n        <hr />\r\n\r\n\r\n");

            
            #line 27 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
         if ((Model.SuggestedVacancies == null || !Model.SuggestedVacancies.Any()) && (Model.SavedAndDraftApplications == null || !Model.SavedAndDraftApplications.Any()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" id=\"find-apprenticeship-btn\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" class=\"button\"");

WriteAttribute("href", Tuple.Create(" href=\'", 1548), Tuple.Create("\'", 1610)
            
            #line 29 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 1555), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipSearch)
            
            #line default
            #line hidden
, 1555), false)
);

WriteLiteral(">Find an apprenticeship</a>\r\n");

            
            #line 30 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
        }
        else
        {
            if (Model.SavedAndDraftApplications != null && Model.SavedAndDraftApplications.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Saved apprenticeships</h2>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                     for (int i = 0; i < Math.Min(3, Model.SavedAndDraftApplications.Count); i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"column-one-third\"");

WriteAttribute("id", Tuple.Create(" id=\"", 2076), Tuple.Create("\"", 2140)
, Tuple.Create(Tuple.Create("", 2081), Tuple.Create("saved-vacancy-", 2081), true)
            
            #line 39 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 2095), Tuple.Create<System.Object, System.Int32>(Model.SavedAndDraftApplications[i].VacancyId
            
            #line default
            #line hidden
, 2095), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 41 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                             if (Model.SavedAndDraftApplications[i].IsPositiveAboutDisability)
                        {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" href=\"https://www.gov.uk/looking-for-work-if-disabled\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2401), Tuple.Create("\"", 2468)
            
            #line 44 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 2407), Tuple.Create<System.Object, System.Int32>(Url.Content("~/content/_assets/img/logo-ticks-small-2x.png")
            
            #line default
            #line hidden
, 2407), false)
);

WriteLiteral(" width=\"37\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </a>\r\n");

            
            #line 46 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2643), Tuple.Create("\"", 2774)
            
            #line 48 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 2650), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipDetails, new {id = Model.SavedAndDraftApplications[i].VacancyId.ToString()})
            
            #line default
            #line hidden
, 2650), false)
);

WriteLiteral(">");

            
            #line 48 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                                                                                        Write(Model.SavedAndDraftApplications[i].Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\r\n                            <p><b>Closing date:</b> ");

            
            #line 49 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                               Write(Model.SavedAndDraftApplications[i].ClosingDate.ToFriendlyClosingToday());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 50 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                             if (@Model.SavedAndDraftApplications[i].ApplicationStatus == ApplicationStatuses.Saved)
                        {

            
            #line default
            #line hidden
WriteLiteral("                                <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3140), Tuple.Create("\"", 3270)
            
            #line 52 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 3147), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipApply, new { id = Model.SavedAndDraftApplications[i].VacancyId.ToString()})
            
            #line default
            #line hidden
, 3147), false)
);

WriteLiteral(">Apply</a></p>\r\n");

            
            #line 53 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3420), Tuple.Create("\"", 3552)
            
            #line 56 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 3427), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipResume, new { id = Model.SavedAndDraftApplications[i].VacancyId.ToString() })
            
            #line default
            #line hidden
, 3427), false)
);

WriteLiteral(">Resume</a></p>\r\n");

            
            #line 57 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 59 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");

            
            #line 61 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
            }
            else if (Model.SuggestedVacancies != null && Model.SuggestedVacancies.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">\r\n                    Similar apprenticeships\r\n                    <span");

WriteLiteral(" class=\"heading-secondary \"");

WriteLiteral(">Also in the ");

            
            #line 66 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                            Write(Model.SuggestedVacanciesCategory);

            
            #line default
            #line hidden
WriteLiteral(" sub-category and within ");

            
            #line 66 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                      Write(Model.SuggestedVacanciesSearchDistance);

            
            #line default
            #line hidden
WriteLiteral(" miles of ");

            
            #line 66 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                                                                       Write(Model.SuggestedVacanciesSearchLocation);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </h2>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n");

            
            #line 69 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                     for (int i = 0; i < Math.Min(3, Model.SuggestedVacancies.Count()); i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"column-one-third\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4343), Tuple.Create("\"", 4404)
, Tuple.Create(Tuple.Create("", 4348), Tuple.Create("suggested-vacancy-", 4348), true)
            
            #line 71 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 4366), Tuple.Create<System.Object, System.Int32>(Model.SuggestedVacancies[i].VacancyId
            
            #line default
            #line hidden
, 4366), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 73 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                             if (Model.SuggestedVacancies[i].IsPositiveAboutDisability)
                        {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" href=\"https://www.gov.uk/looking-for-work-if-disabled\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4658), Tuple.Create("\"", 4725)
            
            #line 76 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 4664), Tuple.Create<System.Object, System.Int32>(Url.Content("~/content/_assets/img/logo-ticks-small-2x.png")
            
            #line default
            #line hidden
, 4664), false)
);

WriteLiteral(" width=\"37\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </a>\r\n");

            
            #line 78 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4900), Tuple.Create("\"", 5024)
            
            #line 80 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 4907), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipDetails, new {id = Model.SuggestedVacancies[i].VacancyId.ToString()})
            
            #line default
            #line hidden
, 4907), false)
);

WriteLiteral(">");

            
            #line 80 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                                                                                 Write(Model.SuggestedVacancies[i].VacancyTitle);

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\r\n                            <p><b>Distance:</b> ");

            
            #line 81 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                           Write(Model.SuggestedVacancies[i].Distance);

            
            #line default
            #line hidden
WriteLiteral(" miles</p>\r\n                        </div>\r\n");

            
            #line 83 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");

            
            #line 85 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
            }

            if (Model.SuggestedVacanciesSearchViewModel != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>View apprenticeships in the <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5401), Tuple.Create("\"", 5553)
            
            #line 89 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 5408), Tuple.Create<System.Object, System.Int32>(Url.ApprenticeshipSearchViewModelRouteUrl(CandidateRouteNames.ApprenticeshipResults, Model.SuggestedVacanciesSearchViewModel)
            
            #line default
            #line hidden
, 5408), false)
, Tuple.Create(Tuple.Create("", 5534), Tuple.Create("&FromSubmitted=true", 5534), true)
);

WriteAttribute("title", Tuple.Create(" title=\"", 5554), Tuple.Create("\"", 5634)
, Tuple.Create(Tuple.Create("", 5562), Tuple.Create("View", 5562), true)
, Tuple.Create(Tuple.Create(" ", 5566), Tuple.Create("apprenticeships", 5567), true)
, Tuple.Create(Tuple.Create(" ", 5582), Tuple.Create("in", 5583), true)
, Tuple.Create(Tuple.Create(" ", 5585), Tuple.Create("sub-category", 5586), true)
, Tuple.Create(Tuple.Create(" ", 5598), Tuple.Create("\'", 5599), true)
            
            #line 89 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                                                                        , Tuple.Create(Tuple.Create("", 5600), Tuple.Create<System.Object, System.Int32>(Model.SuggestedVacanciesCategory
            
            #line default
            #line hidden
, 5600), false)
, Tuple.Create(Tuple.Create("", 5633), Tuple.Create("\'", 5633), true)
);

WriteLiteral(">");

            
            #line 89 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
                                                                                                                                                                                                                                                                                       Write(Model.SuggestedVacanciesCategory);

            
            #line default
            #line hidden
WriteLiteral("</a> sub-category.</p>\r\n");

            
            #line 90 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 93 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
        
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
         if (ViewBag.SearchReturnUrl != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"search-return-link\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5859), Tuple.Create("\"", 5890)
            
            #line 96 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 5866), Tuple.Create<System.Object, System.Int32>(ViewBag.SearchReturnUrl
            
            #line default
            #line hidden
, 5866), false)
);

WriteLiteral(" title=\"Return to search results\"");

WriteLiteral(" id=\"lnk-return-search-results\"");

WriteLiteral(">Return to search results</a>\r\n            </div>\r\n");

            
            #line 98 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <hr />\r\n\r\n        <p>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6062), Tuple.Create("\"", 6089)
            
            #line 102 "..\..\Views\ApprenticeshipApplication\WhatHappensNext.cshtml"
, Tuple.Create(Tuple.Create("", 6069), Tuple.Create<System.Object, System.Int32>(ViewBag.FeedbackUrl
            
            #line default
            #line hidden
, 6069), false)
);

WriteLiteral(" rel=\"external\"");

WriteLiteral(">What did you think of this service?</a>\r\n            <br>(30 second survey, this" +
" will open in a new tab)\r\n        </p>\r\n\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
