// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Collections.Generic;

    /// <summary>
    /// The information related to a Category
    /// </summary>
    public class Category
    {
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category() { }

        /// <summary>
        /// Category class
        /// </summary>
        /// <param name="id"></param>
        /// <param name="fullName"></param>
        /// <param name="codeName"></param>
        /// <param name="parentCategoryCodeName"></param>
        /// <param name="status"></param>
        /// <param name="categoryType"></param>
        /// <param name="subCategories"></param>
        public Category(int id, string fullName, string codeName, string parentCategoryCodeName, string status, string categoryType, IList<Category> subCategories)
        {
            Id = id;
            FullName = fullName;
            CodeName = codeName;
            ParentCategoryCodeName = parentCategoryCodeName;
            Status = status;
            CategoryType = categoryType;
            SubCategories = subCategories;
        }

        /// <summary>
        /// Gets or sets the category's primary identifier
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the category's fullname
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// Gets or sets category's the CodeName  
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CodeName")]
        public string CodeName { get; set; }

        /// <summary>
        /// Gets or sets the category's ParentCategoryCodeName  
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ParentCategoryCodeName")]
        public string ParentCategoryCodeName { get; set; }

        /// <summary>
        /// Gets or sets the category's Status  
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the category's CategoryType  
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CategoryType")]
        public string CategoryType { get; set; }

        /// <summary>
        /// Gets or sets the category's SubCategories 
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SubCategories")]
        public IList<Category> SubCategories { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FullName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "FullName");
            }
            if (CodeName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "CodeName");
            }
            if (ParentCategoryCodeName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ParentCategoryCodeName");
            }
            if (CategoryType == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "CategoryType");
            }
            if (Status == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Status");
            }
        }
    }
}
