// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    public partial class Category
    {
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category() { }

        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        /// <param name="categoryType">Possible values include:
        /// 'SectorSubjectAreaTier1', 'Framework', 'StandardSector',
        /// 'Standard', 'Combined'</param>
        /// <param name="status">Possible values include: 'Active', 'Ceased',
        /// 'PendingClosure'</param>
        public Category(int? id = default(int?), string fullName = default(string), string codeName = default(string), string parentCategoryCodeName = default(string), string categoryType = default(string), string status = default(string), System.Collections.Generic.IList<Category> subCategories = default(System.Collections.Generic.IList<Category>))
        {
            Id = id;
            FullName = fullName;
            CodeName = codeName;
            ParentCategoryCodeName = parentCategoryCodeName;
            CategoryType = categoryType;
            Status = status;
            SubCategories = subCategories;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CodeName")]
        public string CodeName { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ParentCategoryCodeName")]
        public string ParentCategoryCodeName { get; set; }

        /// <summary>
        /// Gets possible values include: 'SectorSubjectAreaTier1',
        /// 'Framework', 'StandardSector', 'Standard', 'Combined'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CategoryType")]
        public string CategoryType { get; private set; }

        /// <summary>
        /// Gets or sets possible values include: 'Active', 'Ceased',
        /// 'PendingClosure'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SubCategories")]
        public System.Collections.Generic.IList<Category> SubCategories { get; private set; }

    }
}
