// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    /// <summary>
    /// Contains a page of live vacancy summaries along with metadata about
    /// the page
    /// </summary>
    public partial class PublicVacancySummariesPage
    {
        /// <summary>
        /// Initializes a new instance of the PublicVacancySummariesPage class.
        /// </summary>
        public PublicVacancySummariesPage() { }

        /// <summary>
        /// Initializes a new instance of the PublicVacancySummariesPage class.
        /// </summary>
        /// <param name="vacancySummaries">The currently requested page of
        /// live vacancy summaries</param>
        /// <param name="totalCount">The total number of live vacancies
        /// available</param>
        /// <param name="currentPage">The currently selected page</param>
        /// <param name="totalPages">The total number of pages of vacancies
        /// available</param>
        public PublicVacancySummariesPage(System.Collections.Generic.IList<PublicVacancySummary> vacancySummaries, int totalCount, int currentPage, int totalPages)
        {
            VacancySummaries = vacancySummaries;
            TotalCount = totalCount;
            CurrentPage = currentPage;
            TotalPages = totalPages;
        }

        /// <summary>
        /// Gets or sets the currently requested page of live vacancy summaries
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "VacancySummaries")]
        public System.Collections.Generic.IList<PublicVacancySummary> VacancySummaries { get; set; }

        /// <summary>
        /// Gets or sets the total number of live vacancies available
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "TotalCount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// Gets or sets the currently selected page
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CurrentPage")]
        public int CurrentPage { get; set; }

        /// <summary>
        /// Gets or sets the total number of pages of vacancies available
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "TotalPages")]
        public int TotalPages { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (VacancySummaries == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "VacancySummaries");
            }
            if (this.VacancySummaries != null)
            {
                foreach (var element in this.VacancySummaries)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
