// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    /// <summary>
    /// The information related to a UK region
    /// </summary>
    public partial class Region
    {
        /// <summary>
        /// Initializes a new instance of the Region class.
        /// </summary>
        public Region() { }

        /// <summary>
        /// Initializes a new instance of the Region class.
        /// </summary>
        /// <param name="regionId">The region's primary identifier</param>
        /// <param name="codeName">The region's code identifier</param>
        /// <param name="shortName">The shortened name of the region. Usually
        /// the same as the code</param>
        /// <param name="fullName">The region's full name</param>
        public Region(int regionId, string codeName, string shortName, string fullName)
        {
            RegionId = regionId;
            CodeName = codeName;
            ShortName = shortName;
            FullName = fullName;
        }

        /// <summary>
        /// Gets or sets the region's primary identifier
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RegionId")]
        public int RegionId { get; set; }

        /// <summary>
        /// Gets or sets the region's code identifier
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CodeName")]
        public string CodeName { get; set; }

        /// <summary>
        /// Gets or sets the shortened name of the region. Usually the same as
        /// the code
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ShortName")]
        public string ShortName { get; set; }

        /// <summary>
        /// Gets or sets the region's full name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CodeName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "CodeName");
            }
            if (ShortName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ShortName");
            }
            if (FullName == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "FullName");
            }
        }
    }
}
