// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    public partial class Sector
    {
        /// <summary>
        /// Initializes a new instance of the Sector class.
        /// </summary>
        public Sector() { }

        /// <summary>
        /// Initializes a new instance of the Sector class.
        /// </summary>
        public Sector(int? id = default(int?), string name = default(string), int? apprenticeshipOccupationId = default(int?), System.Collections.Generic.IList<Standard> standards = default(System.Collections.Generic.IList<Standard>))
        {
            Id = id;
            Name = name;
            ApprenticeshipOccupationId = apprenticeshipOccupationId;
            Standards = standards;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ApprenticeshipOccupationId")]
        public int? ApprenticeshipOccupationId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Standards")]
        public System.Collections.Generic.IList<Standard> Standards { get; set; }

    }
}
