// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Collections.Generic;

    /// <summary>
    /// The information related to a StandardSubjectAreaTierOne
    /// </summary>
    public class StandardSubjectAreaTierOne
    {
        /// <summary>
        /// Initializes a new instance of the StandardSubjectAreaTierOne class.
        /// </summary>
        public StandardSubjectAreaTierOne() { }

        /// <summary>
        /// StandardSubjectAreaTierOne instance class
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <param name="sectors"></param>
        public StandardSubjectAreaTierOne(int id, string name, IEnumerable<Sector> sectors)
        {
            Id = id;
            Name = name;
            Sectors = sectors;
        }

        /// <summary>
        /// Gets or sets the StandardSubjectAreaTierOne's primary identifier
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the StandardSubjectAreaTierOne's name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets StandardSubjectAreaTierOne's sectors 
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Sectors")]
        public IEnumerable<Sector> Sectors { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
