// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    public partial class Standard
    {
        /// <summary>
        /// Initializes a new instance of the Standard class.
        /// </summary>
        public Standard() { }

        /// <summary>
        /// Initializes a new instance of the Standard class.
        /// </summary>
        /// <param name="apprenticeshipLevel">Possible values include:
        /// 'Unknown', 'Intermediate', 'Advanced', 'Higher',
        /// 'FoundationDegree', 'Degree', 'Masters', 'Traineeship'</param>
        /// <param name="status">Possible values include: 'Active', 'Ceased',
        /// 'PendingClosure'</param>
        public Standard(int? id = default(int?), int? apprenticeshipSectorId = default(int?), string name = default(string), string apprenticeshipLevel = default(string), string status = default(string), int? larsCode = default(int?))
        {
            Id = id;
            ApprenticeshipSectorId = apprenticeshipSectorId;
            Name = name;
            ApprenticeshipLevel = apprenticeshipLevel;
            Status = status;
            LarsCode = larsCode;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ApprenticeshipSectorId")]
        public int? ApprenticeshipSectorId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Intermediate',
        /// 'Advanced', 'Higher', 'FoundationDegree', 'Degree', 'Masters',
        /// 'Traineeship'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ApprenticeshipLevel")]
        public string ApprenticeshipLevel { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Active', 'Ceased',
        /// 'PendingClosure'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "LarsCode")]
        public int? LarsCode { get; set; }

    }
}
