// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    public partial class StandardSubjectAreaTierOne
    {
        /// <summary>
        /// Initializes a new instance of the StandardSubjectAreaTierOne class.
        /// </summary>
        public StandardSubjectAreaTierOne() { }

        /// <summary>
        /// Initializes a new instance of the StandardSubjectAreaTierOne class.
        /// </summary>
        public StandardSubjectAreaTierOne(int? id = default(int?), string name = default(string), System.Collections.Generic.IList<Sector> sectors = default(System.Collections.Generic.IList<Sector>))
        {
            Id = id;
            Name = name;
            Sectors = sectors;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Sectors")]
        public System.Collections.Generic.IList<Sector> Sectors { get; set; }

    }
}
