#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Common.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Common.Views.Shared.DisplayTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Privacy.cshtml")]
    public partial class Privacy : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Privacy()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Privacy.cshtml"
  
    ViewBag.Title = "Privacy and cookies - Find an apprenticeship";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"hgroup\"");

WriteLiteral(">\r\n    <h1");

WriteLiteral(" id=\"h1header\"");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Privacy and cookies</h1>\r\n</div>\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Privacy</h2>\r\n    <p>\r\n        This service is run by the Skills Funding Agency " +
"(“SFA”). We’ll handle the information you give to us according to the\r\n        <" +
"a");

WriteLiteral(" href=\"https://www.gov.uk/government/publications/sfa-privacy-notice\"");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(@">Skills Funding Agency personal information charter</a>.
    </p>
    <p>When you register on the service, the personal information you give us will be used:</p>
    <ul>
        <li>so you can apply for an apprenticeship or traineeship</li>
        <li>to match you to apprenticeships/traineeships</li>
        <li>to help provide career support through the National Careers Service</li>
        <li>for administration and research purposes</li>
    </ul>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(@">How long we hold your data</h2>
    <p>If you haven’t signed in for 12 months or activated your account within 30 days of registering we’ll delete your account and remove your personal details. You’ll need to register again to use the service.</p>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(@">Cookies</h2>
    <p>This service puts small files (known as ‘cookies’) on to your computer. Most websites do this. These cookies are used to:</p>
    <ul>
        <li>help us understand how you use the service, so we can improve it</li>
        <li>remember what notifications you’ve seen so you’re not shown them again</li>
        <li>temporarily store the information you enter (eg, your postcode)</li>
    </ul>
    <p>The cookies aren’t used to identify you personally. They’re put on to your computer to make the service work better for you. You can edit or delete the cookies.</p>
    <p>Find out how to <a");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"http://www.aboutcookies.org/\"");

WriteLiteral(">edit and delete cookies</a>.</p>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(@">Webtrends analytics cookies</h2>
    <p>We use Webtrends to collect information about how you use the service. This information helps us to make improvements.</p>
    <p>The Webtrends analytics cookies collect and store information about:</p>
    <ul>
        <li>the pages you visit</li>
        <li>how long you spend on each page</li>
        <li>how you got to the service</li>
        <li>what you click on while you’re using the service</li>
    </ul>
    <p>Webtrends isn’t allowed to use or share our analytics data with anyone, but you can <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2748), Tuple.Create("\"", 2796)
            
            #line 52 "..\..\Views\Home\Privacy.cshtml"
                    , Tuple.Create(Tuple.Create("", 2755), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RouteNames.WebTrendsOptOut)
            
            #line default
            #line hidden
, 2755), false)
);

WriteLiteral(">opt out</a> if you wish.</p>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                WT_FPC
            </td>
            <td>
                Measures the number and volume of visitors
            </td>
            <td>
                2 years
            </td>
        </tr>
        <tr>
            <td>
                ACOOKIE
            </td>
            <td>
                Measures the number and volume of visitors
            </td>
            <td>
                10 years
            </td>
        </tr>
        <tr>
            <td>
                WEBTRENDS_ID
            </td>
            <td>
                Measures the number and volume of visitors
            </td>
            <td>
                10 years
            </td>
        </tr>
        <tr>
            <td>
                WTLOPTOUT
            </td>
            <td>
                Specifies that you have opted out of Webtrends analytics collection
            </td>
            <td>
               5 years
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(@">Measuring website usage (Google Analytics)</h2>
    <p>We also use Google Analytics software to collect information about how you use this service. We do this to help make sure the site is meeting the needs of its users and to help us make improvements.</p>
    <p>We don’t collect or store your personal information (for example, your name or address) so this information can’t be used to identify who you are.</p>
    <p>We don’t allow Google to use or share our analytics data.</p>
    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Google Analytics cookies</h2>\r\n    <p>Google Analytics sets the following cookie" +
"s:</p>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                _ga
            </td>
            <td>
                To help us to understand how you have used the service so that we can administer apprenticeships in England
            </td>
            <td>
                2 years
            </td>
        </tr>
        <tr>
            <td>
                _gat
            </td>
            <td>
                Used to manage the rate at which page view requests are made
            </td>
            <td>
                10 minutes
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Google cookies</h2>\r\n    <p>We use Google Maps to display the location of appren" +
"ticeships/traineeships. Google stores two cookies on your computer for this serv" +
"ice.</p>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                PREF
            </td>
            <td>
                Allows Google to remember preferences such as language and layout.
            </td>
            <td>
                1 year
            </td>
        </tr>
        <tr>
            <td>
                NID
            </td>
            <td>
                Allows Google to customise adverts on its own websites.
            </td>
            <td>
                6 months
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">CloudFlare cookies</h2>\r\n    <p>We use CloudFlare cookies to support the assets " +
"of this service.</p>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                __cfduid
            </td>
            <td>
                Used to override security restrictions the user’s IP address may have.
            </td>
            <td>
                2 years
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Session cookies</h2>\r\n    <p>We store session cookies on your computer to help k" +
"eep your information secure while you use the service.</p>\r\n    <table>\r\n       " +
" <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col />\r\n        </colgroup>\r\n        <thead>\r\n            <tr>\r" +
"\n                <th>\r\n                    Name\r\n                </th>\r\n        " +
"        <th>\r\n                    Purpose\r\n                </th>\r\n              " +
"  <th>\r\n                    Expires\r\n                </th>\r\n            </tr>\r\n " +
"       </thead>\r\n        <tr>\r\n            <td>\r\n                User.Data\r\n    " +
"        </td>\r\n            <td>\r\n                Stores the session id and setti" +
"ngs of a signed in user that are lost when the session ends.\r\n            </td>\r" +
"\n            <td>\r\n                Session\r\n            </td>\r\n        </tr>\r\n  " +
"      <tr>\r\n            <td>\r\n                User.Context\r\n            </td>\r\n " +
"           <td>\r\n                Stores the email address and full name of a sig" +
"ned in user.\r\n            </td>\r\n            <td>\r\n                Session\r\n    " +
"        </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                Us" +
"er.Auth\r\n            </td>\r\n            <td>\r\n                Stores encrypted i" +
"nformation that is used by the server to identify the signed in user.\r\n         " +
"   </td>\r\n            <td>\r\n                2 hours\r\n            </td>\r\n        " +
"</tr>\r\n        <tr>\r\n            <td>\r\n                NAS.SearchResultsDetails\r" +
"\n            </td>\r\n            <td>\r\n                Stores settings used to cu" +
"stomise the display of search results for your user.\r\n            </td>\r\n       " +
"     <td>\r\n                Session\r\n            </td>\r\n        </tr>\r\n    </tabl" +
"e>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(@">Introductory message cookies</h2>
    <p>When you first use the service, you may see pop-up ‘welcome’ or ‘help’ messages. Once you’ve seen one of these, we store a cookie on your computer so it knows not to show it to you again.</p>
    <table>
        <colgroup>
            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                NAS.DisplayEuCookieDirective
            </td>
            <td>
                Saves a message to let us know you've seen our cookie message.
            </td>
            <td>
                12 months
            </td>
        </tr>
        <tr>
            <td>
                NAS.CookieDetection
            </td>
            <td>
                Determines whether the user has cookies enabled.
            </td>
            <td>
                12 months
            </td>
        </tr>
        <tr>
            <td>
                NAS.Help
            </td>
            <td>
                Saves a message to let us know you've seen our help guides.
            </td>
            <td>
                12 months
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(@">Dismissable message cookies</h2>
    <p>We will make you aware of planned outages with pop-up messages. These messages can be dismissed and, when dismissed we store a cookie on your computer so it knows not to show it to you again.</p>
    <table>
        <colgroup>
            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                NAS.DismissPlannedOutageMessage
            </td>
            <td>
                Lets us know that you don't want to see our planned outage message.
            </td>
            <td>
                18 hours
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Multi-language Appnexus</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                pll_language
            </td>
            <td>
                Used for remembering selected language option.
            </td>
            <td>
                1 year
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Appnexus</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                uuid2
            </td>
            <td>
                This cookie contains a unique randomly-generated value that enables the Platform to distinguish browsers and devices. It is matched against information – such as advertising interest segments and histories of ads shown in the browser or device – provided by clients or other third parties and stored on the Platform. This information is used by clients to select advertisements for delivery by the Platform, and to measure the performance of, and attribute payment for, those advertisements. In addition, to enable clients to use non-PII they collect outside the Platform or acquire from other third parties, this cookie is sometimes matched to clients’ or other third parties’ cookies that contain such non-PII. For more information about information collected and used on the Platform, see our <a");

WriteLiteral(" href=\"https://www.appnexus.com/en/company/platform-privacy-policy\"");

WriteLiteral(@">platform privacy page</a>. 
            </td>
            <td>
                18 months
            </td>
        </tr>
        <tr>
            <td>
                uuid2 (opt out)
            </td>
            <td>
                When a user opts out of having the Platform used to select ads based on online behaviour, the unique value in uuid2 is deleted and replaced with the non-unique value “-1”. For more information about the Platform opt out, <a");

WriteLiteral(" href=\"https://www.appnexus.com/en/company/platform-privacy-policy\"");

WriteLiteral(">click here</a>. \r\n            </td>\r\n            <td>\r\n                18 months" +
"\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n            " +
"    sess\r\n            </td>\r\n            <td>\r\n                The sess cookie c" +
"ontains a single non-unique value: “1”. It is used by the Platform to test wheth" +
"er a browser is configured to accept cookies from AppNexus.\r\n            </td>\r\n" +
"            <td>\r\n                18 months\r\n            </td>\r\n        </tr>\r\n " +
"       <tr>\r\n            <td>\r\n                icu\r\n            </td>\r\n         " +
"   <td>\r\n                The icu cookie is used to select ads and limit the numb" +
"er of times a user sees a particular ad. It contains information such as the num" +
"ber of times an ad has been shown, how recently an ad has been shown, or how man" +
"y total ads have been shown.\r\n            </td>\r\n            <td>\r\n             " +
"   18 months\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n" +
"                anj\r\n            </td>\r\n            <td>\r\n                The an" +
"j cookie contains data denoting whether a cookie ID is synced with our partners." +
" ID syncing enables our partners to use their data from outside the Platform on " +
"the Platform. \r\n            </td>\r\n            <td>\r\n                18 months\r\n" +
"            </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n              " +
"  token\r\n            </td>\r\n            <td>\r\n                Cookies that start" +
" with token are helper cookies used as a security measure with industry opt-out " +
"pages. They contain a unique value only to verify the origin of opt-out requests" +
".\r\n            </td>\r\n            <td>\r\n                18 months\r\n            <" +
"/td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                acb\r\n      " +
"      </td>\r\n            <td>\r\n                Cookies that begin with acb have " +
"a value unique to a particular ad and are used to indicate to the Platform which" +
" ad to\r\n            </td>\r\n            <td>\r\n                18 months\r\n        " +
"    </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                PHPSES" +
"SID\r\n            </td>\r\n            <td>\r\n                This cookie is used fo" +
"r managing sessions of visitors to the www.adnxs.com website, which is intended " +
"for use by AppNexus employees. This cookie is used for administrative purposes. " +
"It is not set by the Platform or used for advertising purposes.\r\n            </t" +
"d>\r\n            <td>\r\n                18 months\r\n            </td>\r\n        </tr" +
">\r\n    </table>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Double click</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col />\r\n        </colgroup>\r\n        <thead>\r\n            <tr>\r" +
"\n                <th>\r\n                    Name\r\n                </th>\r\n        " +
"        <th>\r\n                    Purpose\r\n                </th>\r\n              " +
"  <th>\r\n                    Expires\r\n                </th>\r\n            </tr>\r\n " +
"       </thead>\r\n        <tr>\r\n            <td>\r\n                Preferences\r\n  " +
"          </td>\r\n            <td>\r\n                These cookies allow our websi" +
"tes to remember information that changes the way the site behaves or looks, such" +
" as your preferred language or the region you are in. For instance, by rememberi" +
"ng your region, a website may be able to provide you with local weather reports " +
"or traffic news. These cookies can also assist you in changing text size, font, " +
"and other parts of web pages that you can personalize.\r\n                Loss of " +
"the information stored in a preference cookie may make the website experience le" +
"ss functional but should not prevent it from working.\r\n                Most Goog" +
"le users will have a preferences cookie called ‘NID’ in their browsers. A browse" +
"r sends this cookie with requests to Google’s sites. The NID cookie contains a u" +
"nique ID Google uses to remember your preferences and other information, such as" +
" your preferred language (e.g. English), how many search results you wish to hav" +
"e shown per page (e.g. 10 or 20), and whether or not you wish to have Google’s S" +
"afeSearch filter turned on.\r\n            </td>\r\n            <td>\r\n              " +
"  30 Days\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n   " +
"             Security\r\n            </td>\r\n            <td>\r\n                We u" +
"se security cookies to authenticate users, prevent fraudulent use of login crede" +
"ntials, and protect user data from unauthorized parties.\r\n                For ex" +
"ample, we use cookies called ‘SID’ and ‘HSID’ which contain digitally signed and" +
" encrypted records of a user’s Google account ID and most recent sign-in time. T" +
"he combination of these two cookies allows us to block many types of attack, suc" +
"h as attempts to steal the content of forms that you complete on web pages.\r\n   " +
"         </td>\r\n            <td>\r\n                30 Days\r\n            </td>\r\n  " +
"      </tr>\r\n        <tr>\r\n            <td>\r\n                Processes\r\n        " +
"    </td>\r\n            <td>\r\n                Process cookies help make the websi" +
"te work and deliver services that the website visitor expects, like navigating a" +
"round web pages or accessing secure areas of the website. Without these cookies," +
" the website cannot function properly.\r\n                For example, we use a co" +
"okie called ‘lbcs’ which makes it possible for Google Docs to open many Docs in " +
"one browser. Blocking this cookie would prevent Google Docs from operating corre" +
"ctly.\r\n            </td>\r\n            <td>\r\n                30 Days\r\n           " +
" </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                Advertisi" +
"ng\r\n            </td>\r\n            <td>\r\n                We use cookies to make " +
"advertising more engaging to users and more valuable to publishers and advertise" +
"rs. Some common applications of cookies are to select advertising based on what’" +
"s relevant to a user; to improve reporting on campaign performance; and to avoid" +
" showing ads the user has already seen.\r\n                Google uses cookies lik" +
"e NID and SID to help customize ads on Google properties, like Google Search. Fo" +
"r example, we use such cookies to remember your most recent searches, your previ" +
"ous interactions with an advertiser’s ads or search results, and your visits to " +
"an advertiser’s website. This helps us to show you customized ads on Google.\r\n  " +
"              We also use cookies for advertising we serve across the web. Our m" +
"ain advertising cookie on non-Google sites is named ‘id’ or ‘IDE‘ and is stored " +
"in browsers under the domain doubleclick.net. We use other cookies with names su" +
"ch as DSID, FLC, AID, TAID, and exchange_uid. Other Google properties, like YouT" +
"ube, may also use these cookies to show you more relevant ads.\r\n                " +
"Sometimes an advertising cookie may be set on the domain of the site you\'re visi" +
"ting. In the case of our DoubleClick product, a cookie named ‘__gads’ may be set" +
" on the domain of the site you\'re visiting. Unlike cookies that are set on Googl" +
"e\'s own domains, this cookie can\'t be read by Google when you\'re on other sites." +
" It serves purposes such as measuring interactions with the ads on that domain a" +
"nd preventing the same ads from being shown to you too many times.\r\n            " +
"    Google also uses conversion cookies, whose main purpose is to help advertise" +
"rs determine how many times people who click on their ads end up purchasing thei" +
"r products. These cookies allow Google and the advertiser to determine that you " +
"clicked the ad and later visited the advertiser\'s site. Conversion cookies are n" +
"ot used by Google for personalized ad targeting and persist for a limited time o" +
"nly. A cookie named ‘Conversion‘ is dedicated to this purpose. It\'s generally se" +
"t in the googleadservices.com domain (you can find a list of domains we use for " +
"advertising cookies at the foot of this page). Some of our other cookies may be " +
"used to measure conversion events as well. For example, DoubleClick and Google A" +
"nalytics cookies may also be used for this purpose.\r\n                We also use" +
" cookies named ‘AID‘ and ‘TAID‘, which are used to link your activity across dev" +
"ices if you’ve previously signed in to your Google Account on another device. We" +
" do this to coordinate the ads you see across devices and measure conversion eve" +
"nts. These cookies may be set on the domains google.com/ads, google.com/ads/meas" +
"urement, or googleadservices.com. If you don\'t want the ads you see to be coordi" +
"nated across your devices, you can opt out of Ads Personalization using Ads Sett" +
"ings.\r\n            </td>\r\n            <td>\r\n                30 Days\r\n           " +
" </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                Session S" +
"tate\r\n            </td>\r\n            <td>\r\n                Websites often collec" +
"t information about how users interact with a website. This may include the page" +
"s users visit most often and whether users get error messages from certain pages" +
". We use these so-called ‘session state cookies’ to help us improve our services" +
", in order to improve our users’ browsing experience. Blocking or deleting these" +
" cookies will not render the website unusable. These cookies may also be used to" +
" anonymously measure the effectiveness of PPC (pay per click) and affiliate adve" +
"rtising. For example, we use a cookie called ‘recently_watched_video_id_list’ so" +
" that YouTube can record the videos most recently watched by a particular browse" +
"r.\r\n            </td>\r\n            <td>\r\n                30 Days\r\n            </" +
"td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                Analytics\r\n " +
"           </td>\r\n            <td>\r\n                Google Analytics is Google’s" +
" analytics tool that helps website and app owners to understand how their visito" +
"rs engage with their properties. It may use a set of cookies to collect informat" +
"ion and report website usage statistics without personally identifying individua" +
"l visitors to Google. The main cookie used by Google Analytics is the ‘__ga’ coo" +
"kie.\r\n                In addition to reporting website usage statistics, Google " +
"Analytics can also be used, together with some of the advertising cookies descri" +
"bed above, to help show more relevant ads on Google properties (like Google Sear" +
"ch) and across the web. Learn more about Analytics cookies and privacy informati" +
"on.\r\n            </td>\r\n            <td>\r\n                30 Days\r\n            <" +
"/td>\r\n        </tr>\r\n    </table>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Facebook</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                Facebook Pixel (ID:603196216546448)
            </td>
            <td>
                To track the effectiveness of our online advertising
            </td>
            <td>
                30 Days
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">LinkedIn</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                LinkedIn Insight Tag/Pixel
            </td>
            <td>
                To track the effectiveness of our online advertising
            </td>
            <td>
                30 Days
            </td>
        </tr>
    </table>
</section>

<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Radium One</h2>\r\n    <table>\r\n        <colgroup>\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t60\"");

WriteLiteral(" />\r\n            <col");

WriteLiteral(" class=\"t20\"");

WriteLiteral(@" />
            <col />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Expires
                </th>
            </tr>
        </thead>
        <tr>
            <td>
                gwallet.com
            </td>
            <td>
                Build up audience segment based on those who visit landing page
            </td>
            <td>
                1 year
            </td>
        </tr>
    </table>
</section>");

        }
    }
}
#pragma warning restore 1591
