#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Application
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Application/MonitoringInformation.cshtml")]
    public partial class MonitoringInformation : System.Web.Mvc.WebViewPage<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Application.ApplicationViewModel>
    {
        public MonitoringInformation()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
Write(Html.DisplayFor(m => m.ApplicantDetails.DisabilityStatus, "Application/DisabilityStatusQuestion"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Is there anything we can do to support your interview?</h3>\r\n");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
 if (Model.VacancyQuestionAnswers.HasAnythingWeCanDoToSupportYourInterviewAnswer)
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteAttribute("id", Tuple.Create(" id=\"", 372), Tuple.Create("\"", 463)
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
, Tuple.Create(Tuple.Create("", 377), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.VacancyQuestionAnswers.AnythingWeCanDoToSupportYourInterviewAnswer)
            
            #line default
            #line hidden
, 377), false)
);

WriteLiteral(">");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
                                                                                              Write(Html.DisplayFor(m => m.VacancyQuestionAnswers.AnythingWeCanDoToSupportYourInterviewAnswer));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteAttribute("id", Tuple.Create(" id=\"", 580), Tuple.Create("\"", 671)
            
            #line 13 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
, Tuple.Create(Tuple.Create("", 585), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.VacancyQuestionAnswers.AnythingWeCanDoToSupportYourInterviewAnswer)
            
            #line default
            #line hidden
, 585), false)
);

WriteLiteral(">I don\'t have any interview support requirements</p>\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Application\MonitoringInformation.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
