#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Application
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Application/Qualifications.cshtml")]
    public partial class Qualifications : System.Web.Mvc.WebViewPage<IList<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Application.QualificationViewModel>>
    {
        public Qualifications()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Qualifications</h2>\r\n\r\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
     if (!Model.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" id=\"no-qualifications\"");

WriteLiteral(">Applicant doesn\'t have any qualifications</p>\r\n");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
     foreach (var group in Model.GroupBy(item => item.QualificationType))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h3");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                              Write(Html.Encode(group.Key));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

WriteLiteral("        <table");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <colgroup>\r\n                <col");

WriteLiteral(" class=\"t40\"");

WriteLiteral(">\r\n                <col");

WriteLiteral(" class=\"t25\"");

WriteLiteral(">\r\n                <col");

WriteLiteral(" class=\"t15\"");

WriteLiteral(">\r\n                <col>\r\n            </colgroup>\r\n            <thead>\r\n         " +
"       <tr>\r\n                    <th>\r\n                        <span");

WriteLiteral(" class=\"heading-span\"");

WriteLiteral(">Subject</span>\r\n                    </th>\r\n                    <th>\r\n           " +
"             <span");

WriteLiteral(" class=\"heading-span\"");

WriteLiteral(">Grade</span>\r\n                    </th>\r\n                    <th>\r\n             " +
"           <span");

WriteLiteral(" class=\"heading-span\"");

WriteLiteral(">Year</span>\r\n                    </th>\r\n                </tr>\r\n            </the" +
"ad>\r\n            <tbody>\r\n");

            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                 foreach (var item in group)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 38 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                       Write(item.Subject);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                       Write(QualificationPresenter.GetDisplayGrade(item.Grade, item.IsPredicted));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                       Write(item.Year);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>       \r\n");

            
            #line 50 "..\..\Views\Shared\DisplayTemplates\Application\Qualifications.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("<hr /> ");

        }
    }
}
#pragma warning restore 1591
