#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Application
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Application/TrainingCourses.cshtml")]
    public partial class TrainingCourses : System.Web.Mvc.WebViewPage<IEnumerable<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Application.TrainingCourseViewModel>>
    {
        public TrainingCourses()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Training courses</h2>\r\n\r\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
     if (!Model.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" id=\"no-training-history\"");

WriteLiteral(">Applicant hasn\'t been on any training courses</p>\r\n");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
     foreach (var each in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"training-history-item\"");

WriteLiteral(@">
                <table>
                    <colgroup>
                        <col>
                        <col>
                    </colgroup>
                    <thead>
                        <tr>
                            <th>
                                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Training course</h3>\r\n                            </th>\r\n                       " +
"     <th>\r\n                                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">From</h3>\r\n                            </th>\r\n                            <th>\r\n" +
"                                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">To</h3>\r\n                            </th>\r\n                        </tr>\r\n     " +
"               </thead>\r\n                    <tbody>\r\n                        <t" +
"r>\r\n                            <td>\r\n                                <span");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
                                                    Write(each.Provider);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <br/>\r\n                                <" +
"span");

WriteLiteral(" class=\"secondary-text\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
                                                        Write(each.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"sfa-align-top\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 39 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
                           Write(each.FromDate.GetMonthYearLabel());

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"sfa-align-top\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 42 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
                           Write(each.ToDate.GetMonthYearLabel());

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </tbody>\r\n                </table>\r\n            </div>\r\n");

            
            #line 48 "..\..\Views\Shared\DisplayTemplates\Application\TrainingCourses.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <hr/>");

        }
    }
}
#pragma warning restore 1591
