#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Application
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    #line 1 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.ViewModels.Application;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Application/WorkExperience.cshtml")]
    public partial class WorkExperience : System.Web.Mvc.WebViewPage<IEnumerable<WorkExperienceViewModel>>
    {
        public WorkExperience()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Work experience</h2>\r\n\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
     if (!Model.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" id=\"no-work-experience\"");

WriteLiteral(">Applicant doesn\'t have any work experience</p>\r\n");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
     foreach (WorkExperienceViewModel experience in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"work-history-item\"");

WriteLiteral(">\r\n        <table>\r\n            <colgroup>\r\n                <col/>\r\n             " +
"   <col/>\r\n                <col");

WriteLiteral(" class=\"sfa-align-top\"");

WriteLiteral("/>\r\n            </colgroup>\r\n            <thead>\r\n                <tr>\r\n         " +
"           <th>\r\n                        <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Work experience</h3>\r\n                    </th>\r\n                    <th>\r\n     " +
"                   <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">From</h3>\r\n                    </th>\r\n                    <th>\r\n                " +
"        <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">To</h3>\r\n                    </th>\r\n                </tr>\r\n            </thead>\r" +
"\n            <tbody>\r\n                <tr>\r\n                    <td>\r\n          " +
"              <span");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
                                            Write(experience.Employer);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <br/>\r\n                        <span");

WriteLiteral(" class=\"secondary-text\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
                                                Write(experience.JobTitle);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <br/>\r\n                        <br/>\r\n");

WriteLiteral("                        ");

            
            #line 41 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
                   Write(experience.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"sfa-align-top\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
                   Write(experience.FromDate.GetMonthYearLabel());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"sfa-align-top\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
                   Write(experience.ToDate.GetMonthYearLabel());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </tbody>\r\n       " +
" </table>\r\n    </div>\r\n");

            
            #line 53 "..\..\Views\Shared\DisplayTemplates\Application\WorkExperience.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("<hr/>");

        }
    }
}
#pragma warning restore 1591
