#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Recruit.Views.VacancyPosting
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Raa.Vacancies;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
    using SFA.Apprenticeships.Infrastructure.Presentation;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates;
    using SFA.Apprenticeships.Web.Recruit;
    
    #line 4 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
    using SFA.Apprenticeships.Web.Recruit.Constants;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/VacancyPosting/VacancySubmitted.cshtml")]
    public partial class VacancySubmitted : System.Web.Mvc.WebViewPage<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Vacancy.SubmittedVacancyViewModel>
    {
        public VacancySubmitted()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
  
    ViewBag.Title = "Recruit an Apprentice - Confirmation of submission";

    var vacancyText = Model.VacancyText;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"govuk-box-highlight\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\"bold-large\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                 if (Model.Resubmitted)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 17 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                  Write(vacancyText);

            
            #line default
            #line hidden
WriteLiteral(" resubmitted for approval\r\n");

            
            #line 18 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 21 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                  Write(vacancyText);

            
            #line default
            #line hidden
WriteLiteral(" submitted for approval\r\n");

            
            #line 22 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </h1>\r\n        </div>\r\n        \r\n        <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Next steps</h2>\r\n\r\n");

            
            #line 28 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
         if (Model.IsMultiLocationVacancy)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n                Once your vacancy has been reviewed and approved" +
" by a Skills Funding Agency adviser, it will be split into separate adverts for " +
"each location.\r\n            </p>\r\n");

WriteLiteral("            <p>\r\n                You\'ll be notified via your recruitment homepage" +
" if any changes are necessary before the adverts go live.\r\n            </p>\r\n");

            
            #line 36 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n");

            
            #line 40 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                 if (Model.VacancyType == VacancyType.Traineeship)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("Your traineeship opportunity will now be reviewed by a Skills Funding Agency advi" +
"ser.\r\n");

            
            #line 43 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("Your vacancy advert will now be reviewed by a Skills Funding Agency adviser.\r\n");

            
            #line 47 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                You’ll be notified via your recruitment home page if any changes " +
"are\r\n                necessary before the advert goes live.\r\n            </p>\r\n");

            
            #line 51 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">\r\n            Create another apprenticeship vacancy or traineeship opportunity\r\n" +
"            <span");

WriteLiteral(" class=\"heading-secondary \"");

WriteLiteral(">Use a fresh template or continue with a draft</span>\r\n        </h2>\r\n        <di" +
"v");

WriteLiteral(" class=\"form-group inline sfa-xlarge-top-margin\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2196), Tuple.Create("\"", 2309)
            
            #line 57 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
, Tuple.Create(Tuple.Create("", 2203), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.SelectExistingEmployer, new { providerSiteId = Model.ProviderSiteId })
            
            #line default
            #line hidden
, 2203), false)
);

WriteLiteral(" class=\"button\"");

WriteLiteral(">Start new opportunity or vacancy</a>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2378), Tuple.Create("\"", 2437)
            
            #line 58 "..\..\Views\VacancyPosting\VacancySubmitted.cshtml"
, Tuple.Create(Tuple.Create("", 2385), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.RecruitmentHome)
            
            #line default
            #line hidden
, 2385), false)
);

WriteLiteral(" class=\"button sfa-button-secondary\"");

WriteLiteral(">Return to recruitment home</a>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
